### ISSUE TITLE
font improvements

### ISSUE THREAD

**Issue by trend-1** [Akylas/oss-weather#27]
Great little app you got, thanks.

Some improvements could be made to the ui.

- the gray colour of the cloud overcast % is almost imperceptible while the dark theme is active
- the yellow colour of the UV intensity is imperceptible while the light theme is active
- it would be nice to be able to choose a larger font because on smaller devices it is a bit hard to read

**Comment by RageGamerBoi** [comment]
This could mostly be summed up to "Enlarge the icons and make the text brighter".
Maybe that could be achieved in a similar way to my concept for #7 but in the daily weather list...

**Comment by farfromrefug** [comment]
@trend-1 @RageGamerBoi i am working on a "font scale" setting so that you can adjust to your liking.
As for the colors i will look at it

**Comment by trend-1** [comment]
@farfromrefug Sounds great !

Looking forward to it.

**Comment by farfromrefug** [comment]
@trend-1 @RageGamerBoi new release coming really soon with basic font scale setting available through the app bottom sheet menu. Let me know what you think

**Comment by RageGamerBoi** [comment]
Oh, wow, it works really well!
Everything moves without overlapping too.
I like it a lot :)

**Comment by RageGamerBoi** [comment]
I've discovered a bit of an overlap at normal scale on my device; the temperature and the high/low temperature readouts are on top of one another.

**Comment by farfromrefug** [comment]
@RageGamerBoi could you share a screenshot of where it fails ?

**Comment by RageGamerBoi** [comment]
Before the font change it looked as you would expect.
Regular resolution:

![Screenshot_20230421-074103-074](https://user-images.githubusercontent.com/105567407/233645603-ec368973-2604-4e55-984a-bc0ea45e4afb.png)

1.6x Scale:

![Screenshot_20230421-074036-007](https://user-images.githubusercontent.com/105567407/233645450-c6981dfe-e74f-471e-9a62-4bc68bfe23e3.png)

**Comment by farfromrefug** [comment]
@RageGamerBoi thanks! i cant do much about the ones with "updated" and daily icons overlapping temperature. But i should have fixed the first one in the next release

**Comment by RageGamerBoi** [comment]
Great! :+1:

**Comment by farfromrefug** [comment]
@RageGamerBoi btw i am also thinking about resizing daily items height based on font scale (like it is done in hourly view). What do you think?

**Comment by RageGamerBoi** [comment]
That sounds great!

**Comment by trend-1** [comment]
Font sizes above 1.7 are starting to overlap, especially the larger day fonts (date, short description and temperature).

Also cloud coverage with a lower percentage (e.g. 26%) is almost imperceptible in both light and dark themes. (Just to give @farfromrefug  a bit more specific info regarding this topic.)

Otherwise good implementation. Nicely done 👍

**Comment by farfromrefug** [comment]
@trend-1 i made cloud colors a bit more visible but it is intended to be much less visible if there is almost no cloud.
I fixed colors i think ;)
As for the max font scale yes it will fail at a certain scale. I could block it at a certain level but then people with big phones would be blocked when for them it would not overlap

**Comment by trend-1** [comment]
Max font scale: 
- I understand
- Just wanted to let you know my "test results"
- Works for me!

Colors:
- I understand the philosophy
- Perhaps you could opt for *better readable text*
    - What's the use of giving information if not  visible?

**Comment by farfromrefug** [comment]
@RageGamerBoi my idea about cloud color is that i dont want my attention to get onto cloud icon and cover % if  there is no (or almost no) clouds. Most of the time i tend to not read data and rely on colors/icons

**Comment by trend-1** [comment]
@farfromrefug  I understand the philosophy.

- This could be interesting information to others
- It would make more sense imo to make use of a threshold 
    - that way the "fading effect" is still present (demanding less attention)
    - the information is still visible to those who need it

**Comment by RageGamerBoi** [comment]
@trend-1 @farfromrefug What about having the text's minimum transparency be 50%, while the icon can still go to 0%?
